# Module 3: Data Structures Assignments
## Lesson 3.2: Tuples
### Assignment 1: Creating and Accessing Tuples

Create a tuple with the first 10 positive integers. Print the tuple.

In [3]:
tupe=(1,2,3,4,5,6,7,8,9,10)
print(tupe)

<class 'tuple'>


### Assignment 2: Accessing Tuple Elements

Print the first, middle, and last elements of the tuple created in Assignment 1.

In [4]:
tupe=(1,2,3,4,5,6,7,8,9,10)
first,*middle,last=tupe
print(first)
print(middle)
print(last)

1
[2, 3, 4, 5, 6, 7, 8, 9]
10


### Assignment 3: Tuple Slicing

Print the first three elements, the last three elements, and the elements from index 2 to 5 of the tuple created in Assignment 1.

In [5]:
t = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

print("First three elements:", t[:3])
print("Last three elements:", t[-3:])
print("Elements from index 2 to 5:", t[2:6])

First three elements: (1, 2, 3)
Last three elements: (8, 9, 10)
Elements from index 2 to 5: (3, 4, 5, 6)


### Assignment 4: Nested Tuples

Create a nested tuple representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

In [6]:
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

for row in matrix:
    print(row)

print("Element at second row, third column:", matrix[1][2])

(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
Element at second row, third column: 6

### Assignment 5: Tuple Concatenation

Concatenate two tuples: (1, 2, 3) and (4, 5, 6). Print the resulting tuple.

In [10]:
a=(1,2,3)
b=(4,5,6)
c=a+b
print(c)

(1, 2, 3, 4, 5, 6)

### Assignment 6: Tuple Methods

Create a tuple with duplicate elements and count the occurrences of an element. Find the index of the first occurrence of an element in the tuple.

In [12]:
a = (1, 2, 3, 2, 4, 2, 5)

count = a.count(2)
index = a.index(2)

print("Count of 2:", count)
print("First index of 2:", index)

Count of 2: 3
First index of 2: 1


### Assignment 7: Unpacking Tuples

Create a tuple with 5 elements and unpack it into 5 variables. Print the variables.

In [13]:
t = (10, 20, 30, 40, 50)

a, b, c, d, e = t

print(a)
print(b)
print(c)
print(d)
print(e)

10
20
30
40
50


### Assignment 8: Tuple Conversion

Convert a list of the first 5 positive integers to a tuple. Print the tuple.

In [14]:
lst = [1, 2, 3, 4, 5]

t = tuple(lst)

print(t)

(1, 2, 3, 4, 5)


### Assignment 9: Tuple of Tuples

Create a tuple containing 3 tuples, each with 3 elements. Print the tuple of tuples.

In [15]:
a = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

print(a)

((1, 2, 3), (4, 5, 6), (7, 8, 9))

### Assignment 10: Tuple and List

Create a tuple with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a tuple. Print the resulting tuple.

In [17]:
a = (1, 2, 3, 4, 5)

lst = list(a)
lst.append(6)
t = tuple(lst)

print(t)

(1, 2, 3, 4, 5, 6)

### Assignment 11: Tuple and String

Create a tuple with the characters of a string. Join the tuple elements into a single string. Print the string.

In [19]:
s = "hello"

a = tuple(s)
result = ''.join(a)

print(result)

hello

### Assignment 12: Tuple and Dictionary

Create a dictionary with tuple keys and integer values. Print the dictionary.

In [21]:
a = {
    (1, 2): 10,
    (3, 4): 20,
    (5, 6): 30
}

print(d)

{(1, 2): 10, (3, 4): 20, (5, 6): 30}

### Assignment 13: Nested Tuple Iteration

Create a nested tuple and iterate over the elements, printing each element.

In [24]:
a = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

for row in a:
    for item in row:
        print(item)

1
2
3
4
5
6
7
8
9

### Assignment 14: Tuple and Set

Create a tuple with duplicate elements. Convert it to a set to remove duplicates and print the resulting set.

In [25]:
a = (1, 2, 2, 3, 4, 4, 5)

s = set(a)

print(s)

{1, 2, 3, 4, 5}

### Assignment 15: Tuple Functions

Write functions that take a tuple and return the minimum, maximum, and sum of the elements. Print the results for a sample tuple.

In [27]:
def tuple_op(t):
    return min(t), max(t), sum(t)

sample = (5, 2, 9, 1, 7)

minimum, maximum, total = tuple_op(sample)

print("Minimum:", minimum)
print("Maximum:", maximum)
print("Sum:", total)

Minimum: 1
Maximum: 9
Sum: 24